#! /bin/sh
# javac a2/server/TLSServer.java
java TLSServer 8087 "/Users/lee/Dropbox/NS/assn2/programming/s.ks" "sstorepass" "skeypass" "/Users/lee/Dropbox/NS/assn2/programming/strust.ks" "struststorepass"