#! /bin/sh
# javac a2/client/TLSClient.java
java TLSClient 127.0.0.1 8087 "/Users/lee/Dropbox/NS/assn2/programming/c.ks" "cstorepass" "ckeypass" "/Users/lee/Dropbox/NS/assn2/programming/ctrust.ks" "ctruststorepass"